"""add improvement owner

Revision ID: 060ea930df4e
Revises: 6c6469825ea0
Create Date: 2026-08-25 16:58:29.725709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060ea930df4e'
down_revision = '6c6469825ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_employee_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_improvements_owner_employee_id'), ['owner_employee_id'], unique=False)
        batch_op.create_foreign_key(None, 'employees', ['owner_employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_improvements_owner_employee_id'))
        batch_op.drop_column('owner_employee_id')

    # ### end Alembic commands ###
