"""add unique constraint improvement assignment authority

Revision ID: 122631c1c670
Revises: bc66b9fb721e
Create Date: 2026-08-25 17:24:25.499216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122631c1c670'
down_revision = 'bc66b9fb721e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_assignment_authorities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_improvement_assignment_authority', ['department_id', 'employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_assignment_authorities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_improvement_assignment_authority', type_='unique')

    # ### end Alembic commands ###
