"""add improvement uniq  pic

Revision ID: 18b848c1dde8
Revises: 3820a9fdc114
Create Date: 2026-08-25 20:18:02.976613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b848c1dde8'
down_revision = '3820a9fdc114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_pics', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_improvement_pic', ['improvement_id', 'employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_pics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_improvement_pic', type_='unique')

    # ### end Alembic commands ###
