"""add issue management

Revision ID: 1df06c035556
Revises: bae4c7f5de10
Create Date: 2026-09-19 07:39:14.338931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df06c035556'
down_revision = 'bae4c7f5de10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('issue_no', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requestor_employee_id', sa.Integer(), nullable=False),
    sa.Column('developer_employee_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requestor_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_developer_employee_id'), ['developer_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_issue_no'), ['issue_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_issues_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_requestor_employee_id'), ['requestor_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)

    op.create_table('issue_attachments',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_attachments_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_attachments_issue_id'))

    op.drop_table('issue_attachments')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_requestor_employee_id'))
        batch_op.drop_index(batch_op.f('ix_issues_priority'))
        batch_op.drop_index(batch_op.f('ix_issues_module'))
        batch_op.drop_index(batch_op.f('ix_issues_issue_no'))
        batch_op.drop_index(batch_op.f('ix_issues_developer_employee_id'))
        batch_op.drop_index(batch_op.f('ix_issues_category'))

    op.drop_table('issues')
    # ### end Alembic commands ###
