"""add improvement approval authority

Revision ID: 20dffdc1f992
Revises: 122631c1c670
Create Date: 2026-08-25 17:41:17.570405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dffdc1f992'
down_revision = '122631c1c670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_approval_authorities',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'employee_id', name='uq_improvement_approval_authority')
    )
    with op.batch_alter_table('improvement_approval_authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_approval_authorities_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_approval_authorities_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_approval_authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_approval_authorities_employee_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_approval_authorities_department_id'))

    op.drop_table('improvement_approval_authorities')
    # ### end Alembic commands ###
