"""add improvement pic

Revision ID: 3820a9fdc114
Revises: 20dffdc1f992
Create Date: 2026-08-25 20:09:20.388698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3820a9fdc114'
down_revision = '20dffdc1f992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_pics',
    sa.Column('improvement_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvement_pics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_pics_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_pics_improvement_id'), ['improvement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_pics_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_pics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_pics_status'))
        batch_op.drop_index(batch_op.f('ix_improvement_pics_improvement_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_pics_employee_id'))

    op.drop_table('improvement_pics')
    # ### end Alembic commands ###
