"""create improvement table

Revision ID: 3b5d0e61b07d
Revises: cc0e4b89dfec
Create Date: 2026-08-15 14:50:31.502971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5d0e61b07d'
down_revision = 'cc0e4b89dfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvements',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('improvement_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('improvement_plan', sa.Text(), nullable=True),
    sa.Column('implementation_result', sa.Text(), nullable=True),
    sa.Column('improvement_cost', sa.Numeric(precision=18, scale=2), nullable=False, comment='Improvement implementation cost'),
    sa.Column('estimated_time_saving', sa.Integer(), nullable=False, comment='Estimated time saving in minutes'),
    sa.Column('estimated_cost_saving', sa.Numeric(precision=18, scale=2), nullable=False, comment='Estimated cost saving'),
    sa.Column('estimated_benefit', sa.Numeric(precision=18, scale=2), nullable=False, comment='Estimated total benefit in monetary value'),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('approved_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvements_approved_by_employee_id'), ['approved_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvements_improvement_no'), ['improvement_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_improvements_problem_id'), ['problem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvements_problem_id'))
        batch_op.drop_index(batch_op.f('ix_improvements_improvement_no'))
        batch_op.drop_index(batch_op.f('ix_improvements_approved_by_employee_id'))

    op.drop_table('improvements')
    # ### end Alembic commands ###
