"""add issue clarification

Revision ID: 45c62c307d60
Revises: 1df06c035556
Create Date: 2026-09-19 19:52:46.112569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c62c307d60'
down_revision = '1df06c035556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_clarifications',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('requested_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('responded_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['responded_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_clarifications_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_clarifications_requested_by_employee_id'), ['requested_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_clarifications_responded_by_employee_id'), ['responded_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_clarifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_clarifications_status'))
        batch_op.drop_index(batch_op.f('ix_issue_clarifications_responded_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_issue_clarifications_requested_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_issue_clarifications_issue_id'))

    op.drop_table('issue_clarifications')
    # ### end Alembic commands ###
