"""add attachment type to kaizen attachments

Revision ID: 579d11069ca2
Revises: 7f4c418262b2
Create Date: 2026-08-16 18:45:09.308639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579d11069ca2'
down_revision = '7f4c418262b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_kaizen_attachments_attachment_type'), ['attachment_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_attachments_attachment_type'))
        batch_op.drop_column('attachment_type')

    # ### end Alembic commands ###
