"""add kaizen and kaizen attachment

Revision ID: 662104a9697c
Revises: e55109b32d0f
Create Date: 2026-08-16 11:57:09.873732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662104a9697c'
down_revision = 'e55109b32d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizens',
    sa.Column('kaizen_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('improvement_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('before_condition', sa.Text(), nullable=True),
    sa.Column('before_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('before_unit', sa.String(length=50), nullable=True),
    sa.Column('loss_before', sa.Text(), nullable=True),
    sa.Column('after_condition', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('after_unit', sa.String(length=50), nullable=True),
    sa.Column('benefit', sa.Text(), nullable=True),
    sa.Column('cost_saving', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('implementation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvements.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizens_approved_by_employee_id'), ['approved_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_improvement_id'), ['improvement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_kaizen_no'), ['kaizen_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_kaizens_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_rejected_by_employee_id'), ['rejected_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizens_status'), ['status'], unique=False)

    op.create_table('kaizen_attachments',
    sa.Column('kaizen_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kaizen_id'], ['kaizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaizen_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_attachments_kaizen_id'), ['kaizen_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_attachments_kaizen_id'))

    op.drop_table('kaizen_attachments')
    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizens_status'))
        batch_op.drop_index(batch_op.f('ix_kaizens_rejected_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_kaizens_problem_id'))
        batch_op.drop_index(batch_op.f('ix_kaizens_kaizen_no'))
        batch_op.drop_index(batch_op.f('ix_kaizens_improvement_id'))
        batch_op.drop_index(batch_op.f('ix_kaizens_employee_id'))
        batch_op.drop_index(batch_op.f('ix_kaizens_department_id'))
        batch_op.drop_index(batch_op.f('ix_kaizens_approved_by_employee_id'))

    op.drop_table('kaizens')
    # ### end Alembic commands ###
