"""Add unique constraint to problem assignment authority

Revision ID: 6c6469825ea0
Revises: 006a5087acbe
Create Date: 2026-08-24 21:34:34.590334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6469825ea0'
down_revision = '006a5087acbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_assignment_authorities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_problem_assignment_authority', ['department_id', 'employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_assignment_authorities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_problem_assignment_authority', type_='unique')

    # ### end Alembic commands ###
