"""create kaizen reporting period

Revision ID: 7f2e95bf8ea5
Revises: 579d11069ca2
Create Date: 2026-08-16 19:39:23.332480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2e95bf8ea5'
down_revision = '579d11069ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizen_reporting_periods',
    sa.Column('period_code', sa.String(length=20), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaizen_reporting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_reporting_periods_period_code'), ['period_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_reporting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_reporting_periods_period_code'))

    op.drop_table('kaizen_reporting_periods')
    # ### end Alembic commands ###
