"""add kaizen category

Revision ID: 7f4c418262b2
Revises: 662104a9697c
Create Date: 2026-08-16 16:37:38.766919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f4c418262b2'
down_revision = '662104a9697c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizen_categories',
    sa.Column('kaizen_category_code', sa.String(length=10), nullable=False),
    sa.Column('kaizen_category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kaizen_category_code'),
    sa.UniqueConstraint('kaizen_category_name')
    )
    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kaizen_category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kaizens_kaizen_category_id'), ['kaizen_category_id'], unique=False)
        batch_op.create_foreign_key(None, 'kaizen_categories', ['kaizen_category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kaizens_kaizen_category_id'))
        batch_op.drop_column('kaizen_category_id')

    op.drop_table('kaizen_categories')
    # ### end Alembic commands ###
