"""create kaizen department targets

Revision ID: 9812aa611011
Revises: 7f2e95bf8ea5
Create Date: 2026-08-16 21:52:17.910775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9812aa611011'
down_revision = '7f2e95bf8ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizen_department_targets',
    sa.Column('reporting_period_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['kaizen_reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporting_period_id', 'department_id', name='uq_kaizen_department_target_period_department')
    )
    with op.batch_alter_table('kaizen_department_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_department_targets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizen_department_targets_reporting_period_id'), ['reporting_period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_department_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_department_targets_reporting_period_id'))
        batch_op.drop_index(batch_op.f('ix_kaizen_department_targets_department_id'))

    op.drop_table('kaizen_department_targets')
    # ### end Alembic commands ###
