"""create kaizen award periods

Revision ID: a283ed8c7168
Revises: 9812aa611011
Create Date: 2026-08-16 22:33:55.316828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a283ed8c7168'
down_revision = '9812aa611011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizen_award_periods',
    sa.Column('award_code', sa.String(length=20), nullable=False),
    sa.Column('award_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaizen_award_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_award_periods_award_code'), ['award_code'], unique=True)

    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_period_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kaizens_award_period_id'), ['award_period_id'], unique=False)
        batch_op.create_foreign_key(None, 'kaizen_award_periods', ['award_period_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kaizens_award_period_id'))
        batch_op.drop_column('award_period_id')

    with op.batch_alter_table('kaizen_award_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_award_periods_award_code'))

    op.drop_table('kaizen_award_periods')
    # ### end Alembic commands ###
