"""add improvement assignment authority

Revision ID: bc66b9fb721e
Revises: 060ea930df4e
Create Date: 2026-08-25 17:19:41.528987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc66b9fb721e'
down_revision = '060ea930df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_assignment_authorities',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvement_assignment_authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_assignment_authorities_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_assignment_authorities_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_assignment_authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_assignment_authorities_employee_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_assignment_authorities_department_id'))

    op.drop_table('improvement_assignment_authorities')
    # ### end Alembic commands ###
