"""Initial database

Revision ID: bfe6df2866cf
Revises: 
Create Date: 2026-08-02 16:38:52.555783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe6df2866cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_attachments',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_attachments_problem_id'), ['problem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_attachments_problem_id'))

    op.drop_table('problem_attachments')
    # ### end Alembic commands ###
