"""Add status to kaizen award period

Revision ID: c06f4ec58c3e
Revises: ecb1856aa507
Create Date: 2026-08-23 10:09:52.480225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06f4ec58c3e'
down_revision = 'ecb1856aa507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_award_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_kaizen_award_periods_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_award_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_award_periods_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
