"""create improvement attachments

Revision ID: e55109b32d0f
Revises: ef53a76f96dd
Create Date: 2026-08-16 07:39:21.497624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55109b32d0f'
down_revision = 'ef53a76f96dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_attachments',
    sa.Column('improvement_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvement_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_attachments_improvement_id'), ['improvement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_attachments_improvement_id'))

    op.drop_table('improvement_attachments')
    # ### end Alembic commands ###
