"""Create kaizen award judge and score tables

Revision ID: ecb1856aa507
Revises: a283ed8c7168
Create Date: 2026-08-17 13:12:33.086354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb1856aa507'
down_revision = 'a283ed8c7168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaizen_award_judges',
    sa.Column('award_period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_period_id'], ['kaizen_award_periods.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaizen_award_judges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_award_judges_award_period_id'), ['award_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizen_award_judges_employee_id'), ['employee_id'], unique=False)

    op.create_table('kaizen_award_scores',
    sa.Column('award_period_id', sa.Integer(), nullable=False),
    sa.Column('kaizen_id', sa.Integer(), nullable=False),
    sa.Column('judge_employee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_period_id'], ['kaizen_award_periods.id'], ),
    sa.ForeignKeyConstraint(['judge_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['kaizen_id'], ['kaizens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_period_id', 'kaizen_id', 'judge_employee_id', name='uq_kaizen_award_score')
    )
    with op.batch_alter_table('kaizen_award_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaizen_award_scores_award_period_id'), ['award_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizen_award_scores_judge_employee_id'), ['judge_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaizen_award_scores_kaizen_id'), ['kaizen_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaizen_award_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_award_scores_kaizen_id'))
        batch_op.drop_index(batch_op.f('ix_kaizen_award_scores_judge_employee_id'))
        batch_op.drop_index(batch_op.f('ix_kaizen_award_scores_award_period_id'))

    op.drop_table('kaizen_award_scores')
    with op.batch_alter_table('kaizen_award_judges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaizen_award_judges_employee_id'))
        batch_op.drop_index(batch_op.f('ix_kaizen_award_judges_award_period_id'))

    op.drop_table('kaizen_award_judges')
    # ### end Alembic commands ###
