"""create number sequences

Revision ID: ef53a76f96dd
Revises: 3b5d0e61b07d
Create Date: 2026-08-15 21:55:43.729032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef53a76f96dd'
down_revision = '3b5d0e61b07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_sequences',
    sa.Column('sequence_name', sa.String(length=50), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_sequences_sequence_name'), ['sequence_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_number_sequences_sequence_name'))

    op.drop_table('number_sequences')
    # ### end Alembic commands ###
